### ISSUE TITLE
EPIC Assemble the monument

### ISSUE THREAD

**Issue by Jblew** [Jblew/fountain-the-cathedral#1]
- [x] #2
- [x] #3
- [ ] #5
- [ ] #4
- [ ] Adapt base for wheels & electric box & reservoir support 
- [ ] Assemble water reservoir with support
- [ ] Install base
- [ ] Install water reservoir
- [ ] Rotate and transport the monument

**Comment by Jblew** [comment]
Descheduled
